version: '2'
services:
        nginx:
            build: ./nginx/.
            hostname: nginx
            restart: always
            ports:
               - "80:80"
               - "443:443"
            depends_on:
               - web
               - db
        web:
            build: ./app/.
            ports:
                - "3000:3000"
            hostname: web
            restart: always
            volumes:
                - ./app:/usr/src/app
                - /web/logs:/root/.npm/_logs 
            links:
                - db
            depends_on:
                - db 
            environment:
                DBURL: "mongodb://db:27017/app"
                AdminEmail: "deepanshu.lulla@gmail.com"
                
        db:
            image: mongo
            restart: always
            hostname: db
            ports:
                - "27017:27017"
            volumes:
                - ./db:/opt/db
                - /data/db:/data/db
                - /var/backups/mongobackups:/backups
            command: bash -c "chmod +x /opt/db/config_db.sh && /opt/db/config_db.sh"
            environment:
                MONGO_INITDB_ROOT_USERNAME: root
                MONGO_INITDB_ROOT_PASSWORD: password
                MONGO_INITDB_DATABASE: app
