version: '2'
services:
        nginx:
            build: ./nginx/.
            hostname: nginx
            restart: always
            ports:
               - "80:80"
               - "443:443"
            depends_on:
               - web
               - db
        web:
            build: ./app/.
            ports:
                - "3000:3000"
            hostname: web
            restart: always
            volumes:
                - ./app:/usr/src/app
                - /web/logs:/root/.npm/_logs 
            links:
                - db
            depends_on:
                - db 
            environment:
                DBURL: "mongodb://db:27017/app"
                AdminEmail: "deepanshu.lulla@gmail.com"
                
        db:
            build: ./db/.
            restart: always
            hostname: db
            ports:
                - "27017:27017"
            volumes:
                - ./db:/opt/db
                - /data/db:/data/db
                - /var/backups/mongobackups:/backups
            command: bash -c "cp /opt/db/mongod.conf /etc/mongod.conf.orig && /usr/bin/mongod --bind_ip_all && echo 'Starting Server...' && find /backups -mtime +7 -exec rm -rf {} && echo 'Removing older backups' && mongodump --out /backups/`date +\"%m-%d-%y\"` && echo 'Backed up DB'"
            # command: bash -c "cp /opt/db/mongod.conf /etc/mongod.conf.orig && /usr/bin/mongod"
 
            environment:
                MONGO_INITDB_ROOT_USERNAME: root
                MONGO_INITDB_ROOT_PASSWORD: password
                MONGO_INITDB_DATABASE: app
